backend = "glx";
vsync = true;
use-damage = true;
detect-client-opacity = true;
detect-rounded-corners = true;
corner-radius = 22;
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.0;
shadow-offset-x = -15;
shadow-offset-y = -15;
fading = true;
fade-in-step = 0.045;
fade-out-step = 0.045;
inactive-opacity = 1.0;
active-opacity = 1.0;
opacity-rule = [ "90:class_g = 'kitty'" ];
shadow-exclude = [ "class_g = 'Polybar'", "window_type = 'dock'", "window_type = 'desktop'" ];
rounded-corners-exclude = [ "class_g = 'Polybar'", "window_type = 'dock'", "window_type = 'desktop'" ];
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.95; focus = true; };
  popup_menu = { opacity = 0.98; };
  dropdown_menu = { opacity = 0.98; };
};

