backend = "glx";
vsync = false;
use-damage = false;
detect-client-opacity = true;
detect-rounded-corners = true;
corner-radius = 20;
shadow = true;
shadow-radius = 15;
shadow-opacity = 0.5;
shadow-offset-x = -15;
shadow-offset-y = -15;
fade-in-step = 0.01;
fade-out-step = 0.01;
inactive-opacity = 1.0;
active-opacity = 1.0;
shadow-exclude = [ "window_type = 'desktop'" ];
rounded-corners-exclude = [ "window_type = 'desktop'" ];
wintypes:
{
  tooltip = { fade = true; shadow = true; shadow-radius = 0; shadow-opacity = 1.0; shadow-offset-x = -20; shadow-offset-y = -20; opacity = 0.8; focus = true; };
  popup_menu = { opacity = 1.0; shadow = false; };
  dropdown_menu = { opacity = 1.0; shadow = false; };
};

