#!/usr/bin/env bash
set -u

data_home=${XDG_DATA_HOME:-"$HOME/.local/share"}
runtime="$data_home/aemdlc-environment/bin"

"$runtime/workspace-init"

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.55
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config normal_border_color '#30384c'
bspc config active_border_color '#6f7c9b'
bspc config focused_border_color '#55d6be'

bspc rule -a 'Gimp' state=floating
bspc rule -a 'Pavucontrol' state=floating center=true
bspc rule -a 'feh' state=floating

"$runtime/session-start" &

