#!/usr/bin/env bash

aem_init_xdg_paths() {
  if [[ $(id -u) -eq "$AEM_UID" ]]; then
    AEM_CONFIG_HOME=${XDG_CONFIG_HOME:-$AEM_HOME/.config}
    AEM_DATA_HOME=${XDG_DATA_HOME:-$AEM_HOME/.local/share}
    AEM_STATE_HOME=${XDG_STATE_HOME:-$AEM_HOME/.local/state}
    AEM_CACHE_HOME=${XDG_CACHE_HOME:-$AEM_HOME/.cache}
  else
    AEM_CONFIG_HOME=$AEM_HOME/.config
    AEM_DATA_HOME=$AEM_HOME/.local/share
    AEM_STATE_HOME=$AEM_HOME/.local/state
    AEM_CACHE_HOME=$AEM_HOME/.cache
  fi
  AEM_PROJECT_CONFIG="$AEM_CONFIG_HOME/$PROJECT_ID"
  AEM_PROJECT_DATA="$AEM_DATA_HOME/$PROJECT_ID"
  AEM_PROJECT_STATE="$AEM_STATE_HOME/$PROJECT_ID"
  AEM_PROJECT_CACHE="$AEM_CACHE_HOME/$PROJECT_ID"
  export AEM_CONFIG_HOME AEM_DATA_HOME AEM_STATE_HOME AEM_CACHE_HOME
  export AEM_PROJECT_CONFIG AEM_PROJECT_DATA AEM_PROJECT_STATE AEM_PROJECT_CACHE
}

