include theme.conf
font_family JetBrainsMono Nerd Font
font_size 11.5
cursor_shape beam
cursor_blink_interval 0.6
scrollback_lines 10000
enable_audio_bell no
confirm_os_window_close 0
background_opacity 1.0
dynamic_background_opacity no
window_padding_width 10
tab_bar_style powerline
tab_powerline_style slanted
shell zsh
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+w close_window
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

